# Picking Details Custom Fields Configuration
# Defines custom fields that can be displayed and used in picking details
# Maps to CustomField[] array in Settings.PickingDetails

PickingDetails:
  # Array of custom field configurations
  # Each field defines data that can be retrieved and displayed for picking operations

  # Example custom field definitions (commented out for reference)
  # Uncomment and configure as needed for your implementation
  
  # - Key: ItemGroup                                    # Unique identifier for the field (required string)
  #   Description: Item Group                           # Human-readable label shown in UI (required string)  
  #   Type: Text                                        # Field data type (required enum: Text, Number, Date)
  #   Query: SELECT ItmsGrpNam FROM OITB WHERE ItmsGrpCod = OITM.ItmsGrpCod  # SQL query to retrieve data (string, JsonIgnore)
  #   GroupBy: OITM.ItmsGrpCod                         # SQL expression for grouping (nullable string, JsonIgnore)
  
  # - Key: Weight
  #   Description: Item Weight (kg)
  #   Type: Number
  #   Query: OITM.BVolume
  #   GroupBy: null
  
  # - Key: LastUpdated
  #   Description: Last Update Date
  #   Type: Date
  #   Query: OITM.UpdateDate
  
  # Active configuration - Marca field
  - Key: Marca                                          # Unique identifier (required string)
    Description: Marca                                  # Display name in UI (required string)
    Type: Text                                          # Data type: Text, Number, or Date (required enum)
    Query: COALESCE(ORDR.U_MARCA, OINV.U_MARCA, OWTQ.U_MARCA)  # SQL query to retrieve data (string, ignored in JSON)
    GroupBy: ORDR.U_MARCA, OINV.U_MARCA, OWTQ.U_MARCA  # SQL grouping expression (nullable string, ignored in JSON)

# Notes:
# - Key: Must be unique across all custom fields
# - Description: This is what will show up in the UI
# - Type: CustomFieldType enum values (Text=0, Number=1, Date=2)  
# - Query: SQL query for data retrieval (marked with [JsonIgnore])
# - GroupBy: SQL grouping expression (marked with [JsonIgnore], nullable)