//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages_es_PA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages_es_PA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Service.ErrorMessages.es-PA", typeof(ErrorMessages_es_PA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parametero &quot;BarCode&quot; (Codigó de Barra) es obligatorio.
        /// </summary>
        internal static string BarCode_is_a_required_parameter {
            get {
                return ResourceManager.GetString("BarCode_is_a_required_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código de barras {0} no coincide con el código de barras del artículo {1}.
        /// </summary>
        internal static string BarCodentoMatchItemCode {
            get {
                return ResourceManager.GetString("BarCodentoMatchItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrador.
        /// </summary>
        internal static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero Borrador.
        /// </summary>
        internal static string DraftNumber {
            get {
                return ResourceManager.GetString("DraftNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontrol documento de compra fuente valido para el artículo {0}.
        /// </summary>
        internal static string GoodsReceiptData_AddItem_No_valid_source_purchase_document_found_for_item__0_ {
            get {
                return ResourceManager.GetString("GoodsReceiptData_AddItem_No_valid_source_purchase_document_found_for_item__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parametero &quot;ID&quot; (Identificación de Transacción) es obligatorio.
        /// </summary>
        internal static string ID_is_a_required_parameter {
            get {
                return ResourceManager.GetString("ID_is_a_required_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artículo {0}, Código de Barras {1} no fue encontrado en los documentos especficos de la transacción.
        /// </summary>
        internal static string ItemBarCode1WasNotFoundInTransactionSpecificDocuments {
            get {
                return ResourceManager.GetString("ItemBarCode1WasNotFoundInTransactionSpecificDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artículo {0}, Código de Barras {1} no es un artículo de compra.
        /// </summary>
        internal static string ItemBarCodeNotPurchaseItem {
            get {
                return ResourceManager.GetString("ItemBarCodeNotPurchaseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parametero &quot;ItemCode&quot; (Codigó de Artículo) es obligatorio.
        /// </summary>
        internal static string ItemCode_is_a_required_parameter {
            get {
                return ResourceManager.GetString("ItemCode_is_a_required_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código de artículo {0} no se encontró en la base de datos.
        /// </summary>
        internal static string ItemCodeWasNotFoundIndatabase {
            get {
                return ResourceManager.GetString("ItemCodeWasNotFoundIndatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineID es un parameter requerido.
        /// </summary>
        internal static string LineID_is_a_required_parameter {
            get {
                return ResourceManager.GetString("LineID_is_a_required_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parametero &quot;PickEntry&quot; es obligatorio.
        /// </summary>
        internal static string PickEntryRequiredParameter {
            get {
                return ResourceManager.GetString("PickEntryRequiredParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrada de Mercancia.
        /// </summary>
        internal static string PurchaseDeliveryNote {
            get {
                return ResourceManager.GetString("PurchaseDeliveryNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cantidad liberada del artículo {0} es menor que la cantidad agregada..
        /// </summary>
        internal static string ReleasedQuantityFromItemIsless {
            get {
                return ResourceManager.GetString("ReleasedQuantityFromItemIsless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La transacción con ID {0} no existe en el sistema.
        /// </summary>
        internal static string TransactionIDNotExists {
            get {
                return ResourceManager.GetString("TransactionIDNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transacción WMS.
        /// </summary>
        internal static string WMSTransaction {
            get {
                return ResourceManager.GetString("WMSTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transacción de WMS #{0}.
        /// </summary>
        internal static string WMSTransactionAlert {
            get {
                return ResourceManager.GetString("WMSTransactionAlert", resourceCulture);
            }
        }
    }
}
