//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Service.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BarCode is a required parameter.
        /// </summary>
        internal static string BarCode_is_a_required_parameter {
            get {
                return ResourceManager.GetString("BarCode_is_a_required_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BarCode {0} does not match with Item {1} BarCode.
        /// </summary>
        internal static string BarCodentoMatchItemCode {
            get {
                return ResourceManager.GetString("BarCodentoMatchItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bin Location {0} is not current warehouse Warehouses.
        /// </summary>
        internal static string BinNotInWarehouse {
            get {
                return ResourceManager.GetString("BinNotInWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bin is a required parameter.
        /// </summary>
        internal static string BinRequiredParameterForWarehouse {
            get {
                return ResourceManager.GetString("BinRequiredParameterForWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bin Location {0} was not found in the database.
        /// </summary>
        internal static string BinWasNotFoundIndatabase {
            get {
                return ResourceManager.GetString("BinWasNotFoundIndatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        internal static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft Number.
        /// </summary>
        internal static string DraftNumber {
            get {
                return ResourceManager.GetString("DraftNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid source purchase document found for item {0}.
        /// </summary>
        internal static string GoodsReceiptData_AddItem_No_valid_source_purchase_document_found_for_item__0_ {
            get {
                return ResourceManager.GetString("GoodsReceiptData_AddItem_No_valid_source_purchase_document_found_for_item__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID is a required parameter.
        /// </summary>
        internal static string ID_is_a_required_parameter {
            get {
                return ResourceManager.GetString("ID_is_a_required_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Counting.
        /// </summary>
        internal static string InventoryCounting {
            get {
                return ResourceManager.GetString("InventoryCounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {0}, Bar Code {1} was not found in transaction specific documents.
        /// </summary>
        internal static string ItemBarCode1WasNotFoundInTransactionSpecificDocuments {
            get {
                return ResourceManager.GetString("ItemBarCode1WasNotFoundInTransactionSpecificDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {0}, Bar Code {1} is not a purchase item.
        /// </summary>
        internal static string ItemBarCodeNotPurchaseItem {
            get {
                return ResourceManager.GetString("ItemBarCodeNotPurchaseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {0}, Bar Code {1} is not a inventory managed item.
        /// </summary>
        internal static string ItemBarCodeNotStockItem {
            get {
                return ResourceManager.GetString("ItemBarCodeNotStockItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemCode is a required parameter.
        /// </summary>
        internal static string ItemCode_is_a_required_parameter {
            get {
                return ResourceManager.GetString("ItemCode_is_a_required_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code {0} was not found in the database.
        /// </summary>
        internal static string ItemCodeWasNotFoundIndatabase {
            get {
                return ResourceManager.GetString("ItemCodeWasNotFoundIndatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {0}, Bar Code {1} is not enabled in Item Master Data, Warehouses.
        /// </summary>
        internal static string ItemNotInWarehouse {
            get {
                return ResourceManager.GetString("ItemNotInWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineID is a required parameter.
        /// </summary>
        internal static string LineID_is_a_required_parameter {
            get {
                return ResourceManager.GetString("LineID_is_a_required_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PickEntry is a required parameter.
        /// </summary>
        internal static string PickEntryRequiredParameter {
            get {
                return ResourceManager.GetString("PickEntryRequiredParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Delivery Note.
        /// </summary>
        internal static string PurchaseDeliveryNote {
            get {
                return ResourceManager.GetString("PurchaseDeliveryNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity is a required parameter.
        /// </summary>
        internal static string Quantity_is_a_required_parameter {
            get {
                return ResourceManager.GetString("Quantity_is_a_required_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released quantity from item {0} is less then added quantity.
        /// </summary>
        internal static string ReleasedQuantityFromItemIsless {
            get {
                return ResourceManager.GetString("ReleasedQuantityFromItemIsless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction with ID {0} does not exists in the system.
        /// </summary>
        internal static string TransactionIDNotExists {
            get {
                return ResourceManager.GetString("TransactionIDNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMS Transaction.
        /// </summary>
        internal static string WMSTransaction {
            get {
                return ResourceManager.GetString("WMSTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMS Incoming Transaction #{0}.
        /// </summary>
        internal static string WMSTransactionAlert {
            get {
                return ResourceManager.GetString("WMSTransactionAlert", resourceCulture);
            }
        }
    }
}
