//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Service.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {0}, Bar Code {1} was not found in transaction specific documents.
        /// </summary>
        internal static string AddItemParameter_Validate_Item__0___Bar_Code__1__was_not_found_in_transaction_specific_documents {
            get {
                return ResourceManager.GetString("AddItemParameter_Validate_Item__0___Bar_Code__1__was_not_found_in_transaction_spe" +
                        "cific_documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BarCode {0} does not match with Item {1} BarCode.
        /// </summary>
        internal static string BarCode__0__does_not_match_with_Item__1__BarCode {
            get {
                return ResourceManager.GetString("BarCode__0__does_not_match_with_Item__1__BarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BarCode is a required parameter.
        /// </summary>
        internal static string BarCode_is_a_required_parameter {
            get {
                return ResourceManager.GetString("BarCode_is_a_required_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        internal static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft Number.
        /// </summary>
        internal static string DraftNumber {
            get {
                return ResourceManager.GetString("DraftNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID is a required parameter.
        /// </summary>
        internal static string ID_is_a_required_parameter {
            get {
                return ResourceManager.GetString("ID_is_a_required_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {0}, Bar Code {1} is not a purchase item.
        /// </summary>
        internal static string Item__0___Bar_Code__1__is_not_a_purchase_item {
            get {
                return ResourceManager.GetString("Item__0___Bar_Code__1__is_not_a_purchase_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code {0} was not found in the database.
        /// </summary>
        internal static string Item_Code__0__was_not_found_in_the_database {
            get {
                return ResourceManager.GetString("Item_Code__0__was_not_found_in_the_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemCode is a required parameter.
        /// </summary>
        internal static string ItemCode_is_a_required_parameter {
            get {
                return ResourceManager.GetString("ItemCode_is_a_required_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineID is a required parameter.
        /// </summary>
        internal static string LineID_is_a_required_parameter {
            get {
                return ResourceManager.GetString("LineID_is_a_required_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Delivery Note.
        /// </summary>
        internal static string PurchaseDeliveryNote {
            get {
                return ResourceManager.GetString("PurchaseDeliveryNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction with ID {0} does not exists in the system.
        /// </summary>
        internal static string Transaction_with_ID__0__does_not_exists_in_the_system {
            get {
                return ResourceManager.GetString("Transaction_with_ID__0__does_not_exists_in_the_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMS Transaction.
        /// </summary>
        internal static string WMSTransaction {
            get {
                return ResourceManager.GetString("WMSTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMS Incoming Transaction #{0}.
        /// </summary>
        internal static string WMSTransactionAlert {
            get {
                return ResourceManager.GetString("WMSTransactionAlert", resourceCulture);
            }
        }
    }
}
